language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - hhvm-nightly
  
matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm-nightly
    - php: hhvm
    - php: 7.0
    
script:
  - composer self-update
  - composer install
  - bin/dev-phpunit
